development:
  adapter: postgresql
  encoding: unicode
  host: "localhost"
  port: 5432
  database: "api_address_book"
  username: "postgres"
  password: "1234"
  prepared_statements: false
  pool: 10
  timeout: 160